version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bcgx_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bcgx_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongo:
    image: mongo:6
    container_name: bcgx_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: bcgx_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo

  backend:
    build: ./backend
    container_name: bcgx_backend
    restart: always
    depends_on:
      - postgres
      - mongo
      - ai-engine
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/health
      MONGODB_URI: mongodb://mongo:27017
      JWT_SECRET: segredo-super-seguro
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  ai-engine:
    build: ./ai-engine
    container_name: bcgx_ai_engine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./ai-engine:/app

volumes:
  postgres_data:
  mongo_data:
  pgadmin_data:
